### ISSUE TITLE
0.29 breaks TSVectorType under SQLite

### ISSUE THREAD

**Issue by briantrice** [kvesteri/sqlalchemy-utils#112]
I have a code base which is PostgreSQL dependent but a subset runs tests in sqlite with our models. A build today picked up the new version and reached a compilation error:

```
Compiler <sqlalchemy.dialects.sqlite.base.SQLiteTypeCompiler object at 0x6740950> can't render element of type <class 'sqlalchemy.dialects.postgresql.base.TSVECTOR'>
```

I'm hoping I can either conditionalize the column definition or just keep using the library the way I have, disabling full-text search facilities when the engine doesn't support the feature. Thanks!

**Comment by kvesteri** [comment]
I wouldn't want to make a TSVector compiler for sqlite since clearly sqlite doesn't have tsvectors. I think you can make your own compiler which compiles tsvector to sqlite specific type but I wouldn't recommend that. Your unit tests lose their purpose if you start hacking them this way. Rather I'd recommend that test your postgresql specific models against postgresql.

**Comment by joshfriend** [comment]
@briantrice I use and recommend [`testing.postgresql`](https://pypi.python.org/pypi/testing.postgresql/) for spinning up temporary PG databases for tests.

**Comment by briantrice** [comment]
I appreciate it and we'll try to implement these suggestions. At the moment, I do have to pin the version while we grapple with changing our testing structure.
