### ISSUE TITLE
Password cannot be compared before commit to DB

### ISSUE THREAD

**Issue by frol** [kvesteri/sqlalchemy-utils#178]
I'm writing tests to my app and I cannot have an in-memory User object with password set on `__init__`.

```python
class User(db.Model):
    password = db.Column(
        sqlalchemy_utils.types.PasswordType(
            max_length=128,
            schemes=('bcrypt', )
        ),
        nullable=False
    )

u = User(password="test_password")
assert u.password == "test_password"
```

The assert fails because `u.password.hash` is None and the `__eq__` implementation returns right away: https://github.com/kvesteri/sqlalchemy-utils/blob/master/sqlalchemy_utils/types/password.py#L47

**Comment by frol** [comment]
Weird enough is that the tests do cover this use-case, so I digged further and discovered that if I copy the same User model to another file outside of my app and do the same reproduction; the copied model works fine, while in the same session the origin User model fails! I don't use any magic if my memory serves me right.

**Comment by frol** [comment]
The only difference I see now is that `context` doesn't get propagated correctly in the original model:

```python
>>> CopyUser(password="qwe").password.context
<weakproxy at 0x7f084b6e2638 to CryptContext at 0x7f0851674e80>

>>> User(password="qwe").password.context
None
```

**Comment by frol** [comment]
Holy cow! I had `force_auto_coercion` after I instantiate `db` instance and all models. Moving `force_auto_coercion` before those fixed the issue.

I'm sorry for the disturbance!

**Comment by mlecours** [comment]
Thank you for pointing that out. I've been trying to figure out my problem for the past hours and have been trying to figure out in what orders call should be done, because I also noticed that even after a flush, if you do a session.query or session.refresh, then the password is like set back to None. That 'bug report' that was not a bug saved me much time (and also declaring a bug report).

Might not be a bug, but I would recommend enhancing documentation. I based myself on examples from:
[SQLAlchemy-Utils - PasswordType](http://sqlalchemy-utils.readthedocs.org/en/latest/data_types.html#module-sqlalchemy_utils.types.password)

But without that 'force_auto_coercion', it would not work properly...
