### ISSUE TITLE
Did sqlalchemy-utils removed Python 2.7 support?

### ISSUE THREAD

**Issue by jmrbcu** [kvesteri/sqlalchemy-utils#461]
Did sqlalchemy-utils removed Python 2.7 support? Because in the docs it says it is supported but I have an import error with version: 0.36.8:

```
>>> import sqlalchemy_utils
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/totaltrack/lib/python2.7/site-packages/sqlalchemy_utils/__init__.py", line 1, in <module>
    from .aggregates import aggregated  # noqa
  File "/usr/local/totaltrack/lib/python2.7/site-packages/sqlalchemy_utils/aggregates.py", line 372, in <module>
    from .functions.orm import get_column_key
  File "/usr/local/totaltrack/lib/python2.7/site-packages/sqlalchemy_utils/functions/__init__.py", line 1, in <module>
    from .database import (  # noqa
  File "/usr/local/totaltrack/lib/python2.7/site-packages/sqlalchemy_utils/functions/database.py", line 3, in <module>
    from collections.abc import Mapping, Sequence
ImportError: No module named abc
>>>
```

**Comment by mcouthon** [comment]
Looks like [they did](https://github.com/kvesteri/sqlalchemy-utils/commit/b43140eeca2630fc893c3e9d8a984cf97538ea68#diff-2adaa5152ab060d04b18f4afdf78174e) in 0.36.7.
Hardcoding the version to 0.36.6 "solves" the problem.

**Comment by techouse** [comment]
Yea, I guess adding this to your `requirements.txt` could fix it

```
sqlalchemy-utils==0.36.6; python_version < "3.0"
sqlalchemy-utils>=0.36.6; python_version >= "3.0"
```

**Comment by YKdvd** [comment]
The [CHANGES.rst file](https://github.com/kvesteri/sqlalchemy-utils/blob/master/CHANGES.rst#0364-2020-04-30) has this for 0.36.4:

> Drop py27 support

Which would make 0.36.3 the last Python 2.7 version, although maybe no incompatible code was adding for a point release or two.  Dropping support for 2.7 is one thing, but the (only?) wheel at PyPI is 

> SQLAlchemy_Utils-0.37.0-py2.py3-none-any.whl 

which is falsely claiming to support py2.  I think [setup.cfg](https://github.com/kvesteri/sqlalchemy-utils/blob/master/setup.cfg) needs to change to `universal=0` in the [bdist_wheel] section to drop the py2 tag from the wheel, so that pip for Python 2.7 doesn't mistakenly think that these newer versions are suitable.

**Comment by jarkkorantala** [comment]
Submitted a PR: https://github.com/kvesteri/sqlalchemy-utils/pull/514

**Comment by graingert** [comment]
@jarkkorantala no the universal flag was fine, the fix is here https://github.com/kvesteri/sqlalchemy-utils/pull/475

**Comment by graingert** [comment]
the `universal = 0` flag still results in `pip install -U sqlalchemy-utils` downloading `SQLAlchemy-Utils-0.37.1.tar.gz` instead of  0.36.6

**Comment by YKdvd** [comment]
Does the setup.py need at python_requires>='3.4' or whatever Py3 version is being supported?  Is that how 
PyPI determine that a source distribution (with no versioning in the filename)  is not valid for pip requests for say 2.7?

**Comment by graingert** [comment]
Yes

**Comment by graingert** [comment]
You also need to yank any version that claims support for py2.7 but doesn't actually support it

**Comment by bmoeskau** [comment]
Much love to open source maintainers doing the Lord's work and all, but I'm just going to leave this here for future reference https://semver.org/

**Comment by graingert** [comment]
> Much love to open source maintainers doing the Lord's work and all, but I'm just going to leave this here for future reference https://semver.org/

`0.` in semver allows breaking changes in every release

**Comment by bmoeskau** [comment]
> > Much love to open source maintainers doing the Lord's work and all, but I'm just going to leave this here for future reference https://semver.org/
> 
> `0.` in semver allows breaking changes in every release

That's a bit of a cop out, if technically true. The spirit of semver is not "make all software 0.x and go nuts". The point is to use versions that actually mean something useful.

On a separate note, it would be great if it was also clear what versions of this lib go with which versions of SQLAlchemy. I'm trying to upgrade multiple things at once, and so far getting the correct version of this lib to play nicely with everything else has proven to be a sticking point.

**Comment by bmoeskau** [comment]
It seems like SQLAlchemy 1.4 support was [added in 0.37.0](https://github.com/kvesteri/sqlalchemy-utils/blob/master/CHANGES.rst#0370-2021-04-12), but since Py2 support was dropped somewhere in 0.36.3-6, I guess I can't upgrade to SA 1.4 without doing some hacking locally....

I am working in a Py2 system (we are working toward upgrading everything to Py3, but as I'm sure you know, it's challenging). Part of the strategy was to upgrade SA to 1.4, then 2.0, as that is [their recommended upgrade path](https://docs.sqlalchemy.org/en/14/changelog/migration_20.html). Since this lib tracks SA, it might have made sense to try to match their Python support a little more carefully. This is making things needlessly harder.
