### ISSUE TITLE
0.36.8 breaks database_exists() call

### ISSUE THREAD

**Issue by pmezard** [kvesteri/sqlalchemy-utils#462]
Hello,

We have code doing something like:
```
url = "postgresql+psycopg2://user:password@localhost/db"
if not sqlalchemy_utils.database_exists(url):
    ....
```
It works with 0.36.7 but fails with 0.36.8 with:
```
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  database "user" does not exist
```
I think the new code attempts to connect to "user" default database, which is "user". Unfortunately, this database does not exist.

Is this a bug, or should we modify our code in any way?

Thanks.

**Comment by oxlade39** [comment]
+1 on this. Seeing the exact same issue after upgrading

**Comment by PJEstrada** [comment]
+1 Have the same issue too.

**Comment by jtbeach** [comment]
Can we have a parameter to database_exists to control which database to connect to in order to perform the check?

**Comment by k4r1** [comment]
This code has been changed recently, originally it connected to `template1` to perform the existence check, that was then changed to `postgres`, and finally [this](https://github.com/kvesteri/sqlalchemy-utils/pull/372) PR removed that logic entirely and instead sets database to `none`.

I think @jtbeach's suggestion makes sense, due to it being difficult to find a database that is guaranteed to exist (and to which connections are allowed) in every single case.

**Comment by k4r1** [comment]
Looks like there's a fix with the suggested behaviour already in a PR: https://github.com/kvesteri/sqlalchemy-utils/pull/463

**Comment by jtbeach** [comment]
> Looks like there's a fix with the suggested behaviour already in a PR: #463

There's a couple of bugs in that PR -- have put a couple of comments on there
